# Generated by Django 4.0.2 on 2022-02-14 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('file', 'file'), ('sql', 'sql_query'), ('ws', 'web_service')], default='file', max_length=32, unique=True)),
                ('path', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=128)),
                ('port', models.IntegerField()),
                ('type_source', models.CharField(max_length=32)),
                ('separator', models.CharField(max_length=4)),
                ('status_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_types', models.JSONField()),
                ('proposed_types', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyllytics.sourcemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveStatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyllytics.sourcemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('type_correlation', models.CharField(max_length=32)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyllytics.sourcemodel')),
            ],
        ),
    ]
