# Generated by Django 4.0.2 on 2022-02-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyllytics', '0002_alter_correlationmodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='correlationmodel',
            table='pyllytics_correlation',
        ),
        migrations.AlterModelTable(
            name='descriptivestatisticsmodel',
            table='pyllytics_descriptive_statistics',
        ),
        migrations.AlterModelTable(
            name='sourcemodel',
            table='pyllytics_source',
        ),
        migrations.AlterModelTable(
            name='sourcetypesmodel',
            table='pyllytics_source_types',
        ),
    ]
