# Generated by Django 4.0.2 on 2022-02-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyllytics', '0003_alter_correlationmodel_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='host',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='separator',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='type_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='user',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
