# Generated by Django 4.0.2 on 2022-02-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyllytics', '0004_sourcemodel_file_alter_sourcemodel_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
