# Generated by Django 4.0.2 on 2022-02-18 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyllytics', '0005_alter_sourcemodel_file_alter_sourcemodel_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivestatisticsmodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyllytics.sourcemodel', unique=True),
        ),
        migrations.AlterField(
            model_name='sourcetypesmodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyllytics.sourcemodel', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='correlationmodel',
            unique_together={('source', 'type_correlation')},
        ),
    ]
