# Generated by Django 4.0.2 on 2022-02-18 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyllytics', '0006_alter_descriptivestatisticsmodel_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivestatisticsmodel',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyllytics.sourcemodel'),
        ),
        migrations.AlterField(
            model_name='sourcetypesmodel',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyllytics.sourcemodel'),
        ),
    ]
